#!/usr/bin/env ksh
#
# orafs<SID>           Start up the <SID> ASM FS of Oracle database
#
# chkconfig:           2345 55 25
# description:         <SID> ASM FS of Oracle database.
#
# processname:         orafs<SID>
# pidfile:             /var/run/oracle/orafs<SID>.pid

### BEGIN INIT INFO
# Provides:            orafs<SID>
# Required-Start:      $local_fs $network $syslog
# Required-Stop:       $local_fs $syslog
# Should-Start:        $syslog
# Should-Stop:         $network $syslog
# Default-Start:       3 5
# Default-Stop:        0 1 2 4 6
# Short-Description:   Start up <SID> ASM FS of Oracle database
# Description:         <SID> ASM FS of Oracle database.
### END INIT INFO

. /etc/rc.d/init.d/orafunctions.sh

SID="<SID>"
DSK=("FRA${SID}" "DATA${SID}")

case ${1} in
    "start")
	for i in ${DSK[*]}; do
	    asmfs_handler mount "${i}"
	done
	;;
    "stop")
	for i in ${DSK[*]}; do
	    asmfs_handler umount "${i}"
	done
	;;
    "status")
	asmfs_status_sid "${SID}"
	;;
esac
